### ISSUE TITLE
Formatting of covariance file in Jax branch

### ISSUE THREAD

**Issue by geotaylo** [djones1040/SALTShaker#249]
Hey, I noticed that there is no linebreak being applied to the covariance files output by the jax branch. I assume this is going to start breaking things if we start to use Jax branch surfaces for lc fitting.

**Comment by darcykenworthy** [comment]
Are you on the latest commit? Should’ve been fixed D’ArcySent from my iPhoneOn Feb 23, 2023, at 9:14 AM, Georgie ***@***.***> wrote:﻿
Hey, I noticed that there is no linebreak being applied to the covariance files output by the jax branch. I assume this is going to start breaking things if we start to use Jax branch surfaces for lc fitting.

**Comment by geotaylo** [comment]
Ah, no I'm not, I'm looking at outputs from a week or so ago. You're one step ahead of me! Thanks.
