### ISSUE TITLE
Conda env issue when running SALTShaker on Midway

### ISSUE THREAD

**Issue by geotaylo** [djones1040/SALTShaker#254]
I'm getting this error related to the SALT3 training when running with submit_batch_jobs on Midway:
pkg_resources.DistributionNotFound: The 'pytest-astropy' distribution was not found and is required by saltshaker

The command to reproduce is submit_batch_jobs.sh $DES_ROOT/SALT3training/training_master_systCovar_unoU.input, and the error shows up in the training logs of the output directory.

**Comment by djones1040** [comment]
just pip installed pytest-astropy, try again?

**Comment by djones1040** [comment]
Maria says this is fixed now :)
